---
- hosts: localhost
  tasks:
    - name: deploy nginx docker container
      docker_container:
        image: naveen412/test:lates
        name: test
        state: started
        auto_remove: true

