---
- hosts: localhost
  tasks:
    - name: pull a docker image
      docker_image:
        name: naveen412/18mar:latest
        source: pull
    - name: run docker image as a container
      docker_container: 
        name: springboot-java
        image: naveen412/18mar:latest
        state: started
        port:
        - "8082:8082"

