# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
- stage: Build
  displayName: Build Stage
  jobs:  
  - job: Build
    displayName: Build 

    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@2
      inputs:
        containerRegistry: 'acrsc'
        repository: 'naveen412/azurepipeline'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'manifests'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifets'
          targetPath: '$(Pipeline.Workspace)/manifests'

      - task: KubernetesManifest@0
        inputs:
           action: 'deploy'
           kubernetesServiceConnection: 'kubesc'
           namespace: 'default'
           manifests:
             $(Pipeline.Workspace)/manifests/springboot-deployment.yml
             $(Pipeline.Workspace)/manifests/springboot-service.yml



    




  