# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
- stage: Build
  displayName: Build Stage
  jobs:  
  - job: Build
    displayName: Build 

    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-sc'
        repository: 'naveen412/yaml-pipeline'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Pay-As-You-Go(d480c57c-6111-439f-a530-21ab541c359c)'
        appName: 'java-naveen1'
        containers: 'naveen412/yaml-pipeline'
        containerCommand: 'docker run naveen412/yaml-pipeline:10'




    




  